version: '2.3'
services:
  redisedge:
    build: ./redisedge
    ports:
      - 6379:6379
  init:
    build: pipert/contrib
    runtime: nvidia
    depends_on:
      - redisedge
    ports:
    - 5000:5000
    command: ['run_contrib_app']

